"""create tabel rule

Revision ID: 1937fc2b8bbb
Revises: ea0b5e34b6dc
Create Date: 2025-06-05 23:21:53.323570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1937fc2b8bbb'
down_revision: Union[str, None] = 'ea0b5e34b6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.CHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('id_penyakit', sa.CHAR(length=5), nullable=True),
    sa.Column('id_gejala', sa.CHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['id_gejala'], ['gejala.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_penyakit'], ['penyakit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule')
    # ### end Alembic commands ###
