"""set unique fields

Revision ID: 42030eef40e7
Revises: ba0cda4f4dfc
Create Date: 2025-05-28 23:41:15.019860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42030eef40e7'
down_revision: Union[str, None] = 'ba0cda4f4dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'gejala', ['nama_gejala'])
    op.create_unique_constraint(None, 'kelompok', ['nama_kelompok'])
    op.create_unique_constraint(None, 'pakar', ['nama_pakar'])
    op.create_unique_constraint(None, 'penyakit', ['nama_penyakit'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'penyakit', type_='unique')
    op.drop_constraint(None, 'pakar', type_='unique')
    op.drop_constraint(None, 'kelompok', type_='unique')
    op.drop_constraint(None, 'gejala', type_='unique')
    # ### end Alembic commands ###
