"""add desc to artibute kelompok

Revision ID: 493c07ab7b82
Revises: 9a929aa90b40
Create Date: 2025-06-08 11:23:03.138523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493c07ab7b82'
down_revision: Union[str, None] = '9a929aa90b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kelompok', sa.Column('deskripsi', sa.Text(), nullable=True))
    op.create_unique_constraint(op.f('uq_pakar_id'), 'pakar', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_pakar_id'), 'pakar', type_='unique')
    op.drop_column('kelompok', 'deskripsi')
    # ### end Alembic commands ###
