"""initial tabel

Revision ID: 9a929aa90b40
Revises: 
Create Date: 2025-06-08 09:57:27.805756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a929aa90b40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gejala',
    sa.Column('id', sa.CHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('pertanyaan', sa.Text(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gejala')),
    sa.UniqueConstraint('nama', name=op.f('uq_gejala_nama'))
    )
    op.create_table('kelompok',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kelompok')),
    sa.UniqueConstraint('nama', name=op.f('uq_kelompok_nama'))
    )
    op.create_table('pakar',
    sa.Column('id', sa.CHAR(length=5), nullable=False),
    sa.Column('nama', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pakar')),
    sa.UniqueConstraint('id', name=op.f('uq_pakar_id')),
    sa.UniqueConstraint('nama', name=op.f('uq_pakar_nama'))
    )
    op.create_table('penyakit',
    sa.Column('id', sa.CHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('solusi', sa.Text(), nullable=False),
    sa.Column('pencegahan', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_penyakit')),
    sa.UniqueConstraint('nama', name=op.f('uq_penyakit_nama'))
    )
    op.create_table('kelompok_gejala',
    sa.Column('id_gejala', sa.CHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id_kelompok', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_gejala'], ['gejala.id'], name=op.f('fk_kelompok_gejala_id_gejala_gejala'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_kelompok'], ['kelompok.id'], name=op.f('fk_kelompok_gejala_id_kelompok_kelompok'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_gejala', 'id_kelompok', name=op.f('pk_kelompok_gejala'))
    )
    op.create_table('rule',
    sa.Column('id', sa.CHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('id_penyakit', sa.CHAR(length=5), nullable=True),
    sa.Column('id_gejala', sa.CHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['id_gejala'], ['gejala.id'], name=op.f('fk_rule_id_gejala_gejala'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_penyakit'], ['penyakit.id'], name=op.f('fk_rule_id_penyakit_penyakit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule'))
    )
    op.create_table('rule_cf',
    sa.Column('id_rule', sa.CHAR(length=5), nullable=False),
    sa.Column('id_pakar', sa.CHAR(length=5), nullable=False),
    sa.Column('nilai', sa.Double(precision=53), nullable=False),
    sa.ForeignKeyConstraint(['id_pakar'], ['pakar.id'], name=op.f('fk_rule_cf_id_pakar_pakar'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rule'], ['rule.id'], name=op.f('fk_rule_cf_id_rule_rule'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_rule', 'id_pakar', name=op.f('pk_rule_cf'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_cf')
    op.drop_table('rule')
    op.drop_table('kelompok_gejala')
    op.drop_table('penyakit')
    op.drop_table('pakar')
    op.drop_table('kelompok')
    op.drop_table('gejala')
    # ### end Alembic commands ###
