"""create tabel rule_cf

Revision ID: 9d313b1dde34
Revises: 1937fc2b8bbb
Create Date: 2025-06-05 23:25:13.090538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d313b1dde34'
down_revision: Union[str, None] = '1937fc2b8bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_cf',
    sa.Column('id_rule', sa.CHAR(length=8), nullable=False),
    sa.Column('id_pakar', sa.CHAR(length=5), nullable=False),
    sa.Column('nilai', sa.Double(precision=53), nullable=False),
    sa.ForeignKeyConstraint(['id_pakar'], ['pakar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rule'], ['rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_rule', 'id_pakar')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_cf')
    # ### end Alembic commands ###
