"""update rule cf

Revision ID: a2e40e0dcdf9
Revises: 7721bfdd8610
Create Date: 2025-06-08 18:11:18.783540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e40e0dcdf9'
down_revision: Union[str, None] = '7721bfdd8610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rule_cf', 'id_rule',
               existing_type=sa.CHAR(length=5),
               type_=sa.CHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rule_cf', 'id_rule',
               existing_type=sa.CHAR(length=8),
               type_=sa.CHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
