"""update type data table

Revision ID: ab951e818105
Revises: a2e40e0dcdf9
Create Date: 2025-06-09 06:30:14.255708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab951e818105'
down_revision: Union[str, None] = 'a2e40e0dcdf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gejala', 'id',
               existing_type=sa.CHAR(length=5),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('kelompok_gejala', 'id_gejala',
               existing_type=sa.CHAR(length=5),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('penyakit', 'id',
               existing_type=sa.CHAR(length=5),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('rule', 'id',
               existing_type=sa.CHAR(length=8),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('rule', 'id_penyakit',
               existing_type=sa.CHAR(length=5),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('rule', 'id_gejala',
               existing_type=sa.CHAR(length=5),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('rule_cf', 'id_rule',
               existing_type=sa.CHAR(length=8),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rule_cf', 'id_rule',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.CHAR(length=8),
               existing_nullable=False)
    op.alter_column('rule', 'id_gejala',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.CHAR(length=5),
               existing_nullable=True)
    op.alter_column('rule', 'id_penyakit',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.CHAR(length=5),
               existing_nullable=True)
    op.alter_column('rule', 'id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.CHAR(length=8),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('penyakit', 'id',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.CHAR(length=5),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('kelompok_gejala', 'id_gejala',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.CHAR(length=5),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('gejala', 'id',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.CHAR(length=5),
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
