"""add_table_kelompok_gejala

Revision ID: ba0cda4f4dfc
Revises: fd8dc35fa285
Create Date: 2025-05-28 22:48:46.504457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0cda4f4dfc'
down_revision: Union[str, None] = 'fd8dc35fa285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelompok',
    sa.Column('id_kelompok', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_kelompok', sa.VARCHAR(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_kelompok')
    )
    op.create_table('kelompok_gejala',
    sa.Column('id_gejala', sa.CHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id_kelompok', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_gejala'], ['gejala.id_gejala'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_kelompok'], ['kelompok.id_kelompok'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_gejala', 'id_kelompok')
    )
    op.drop_column('gejala', 'kategori')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gejala', sa.Column('kategori', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('kelompok_gejala')
    op.drop_table('kelompok')
    # ### end Alembic commands ###
