"""create tabel penyakit

Revision ID: bfcc3b78bf70
Revises: 6baf37f47465
Create Date: 2025-06-05 23:16:48.559683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfcc3b78bf70'
down_revision: Union[str, None] = '6baf37f47465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penyakit',
    sa.Column('id', sa.CHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penyakit')
    # ### end Alembic commands ###
