"""update primary key pakar

Revision ID: cc20e223ef61
Revises: fd6cf2853ffa
Create Date: 2025-06-06 00:32:28.589861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc20e223ef61'
down_revision: Union[str, None] = 'fd6cf2853ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pakar', ['id'])
    op.alter_column('rule_cf', 'id_rule',
               existing_type=sa.CHAR(length=8),
               type_=sa.CHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rule_cf', 'id_rule',
               existing_type=sa.CHAR(length=5),
               type_=sa.CHAR(length=8),
               existing_nullable=False)
    op.drop_constraint(None, 'pakar', type_='unique')
    # ### end Alembic commands ###
