"""create tabel gejala

Revision ID: ea0b5e34b6dc
Revises: bfcc3b78bf70
Create Date: 2025-06-05 23:18:30.390244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0b5e34b6dc'
down_revision: Union[str, None] = 'bfcc3b78bf70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gejala',
    sa.Column('id', sa.CHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gejala')
    # ### end Alembic commands ###
