"""create tabel kelompok_gejala

Revision ID: fd6cf2853ffa
Revises: 9d313b1dde34
Create Date: 2025-06-05 23:28:02.023446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6cf2853ffa'
down_revision: Union[str, None] = '9d313b1dde34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelompok',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('kelompok_gejala',
    sa.Column('id_gejala', sa.CHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id_kelompok', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_gejala'], ['gejala.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_kelompok'], ['kelompok.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_gejala', 'id_kelompok')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kelompok_gejala')
    op.drop_table('kelompok')
    # ### end Alembic commands ###
