"""create_all_tabel

Revision ID: fd8dc35fa285
Revises: 
Create Date: 2025-05-26 19:23:25.264094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8dc35fa285'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gejala',
    sa.Column('id_gejala', sa.CHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('nama_gejala', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('kategori', sa.VARCHAR(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_gejala')
    )
    op.create_table('pakar',
    sa.Column('id_pakar', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_pakar', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_pakar')
    )
    op.create_table('penyakit',
    sa.Column('id_penyakit', sa.CHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('nama_penyakit', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_penyakit')
    )
    op.create_table('rule',
    sa.Column('id_rule', sa.CHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('id_penyakit', sa.CHAR(length=5), nullable=True),
    sa.Column('id_gejala', sa.CHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['id_gejala'], ['gejala.id_gejala'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_penyakit'], ['penyakit.id_penyakit'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_rule')
    )
    op.create_table('rule_cf',
    sa.Column('id_rule', sa.CHAR(length=8), nullable=False),
    sa.Column('id_pakar', sa.Integer(), nullable=False),
    sa.Column('nilai_cf', sa.Double(precision=53), nullable=False),
    sa.ForeignKeyConstraint(['id_pakar'], ['pakar.id_pakar'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rule'], ['rule.id_rule'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_rule', 'id_pakar')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_cf')
    op.drop_table('rule')
    op.drop_table('penyakit')
    op.drop_table('pakar')
    op.drop_table('gejala')
    # ### end Alembic commands ###
